apiVersion: v1
kind: Secret
metadata:
  name: wordpress-credentials
type: Opaque
stringData:
  # ⚠️ Démo uniquement — en prod : utiliser sealed-secrets / sops / external-secrets
  wordpress-password: ChangeMe123!
  mariadb-root-password: RootChangeMe123!
  mariadb-replication-password: ReplChangeMe123!
  mariadb-password: WpDbChangeMe123!
