apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Nutanix Kubernetes Platform - Demo</title>
        <style>
            * { margin: 0; padding: 0; box-sizing: border-box; }
            body {
                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                min-height: 100vh;
                display: flex;
                align-items: center;
                justify-content: center;
                color: white;
            }
            .container {
                text-align: center;
                padding: 3rem;
                background: rgba(255, 255, 255, 0.1);
                border-radius: 20px;
                backdrop-filter: blur(10px);
                box-shadow: 0 8px 32px rgba(0, 0, 0, 0.1);
                border: 1px solid rgba(255, 255, 255, 0.2);
                max-width: 600px;
            }
            h1 {
                font-size: 3rem;
                margin-bottom: 1rem;
                text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.3);
            }
            .subtitle {
                font-size: 1.5rem;
                margin-bottom: 2rem;
                opacity: 0.9;
            }
            .features {
                display: grid;
                grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
                gap: 1rem;
                margin-top: 2rem;
            }
            .feature {
                background: rgba(255, 255, 255, 0.1);
                padding: 1.5rem;
                border-radius: 10px;
                transition: transform 0.3s ease;
            }
            .feature:hover {
                transform: translateY(-5px);
            }
            .emoji {
                font-size: 2rem;
                margin-bottom: 0.5rem;
            }
            .timestamp {
                margin-top: 2rem;
                font-size: 0.9rem;
                opacity: 0.7;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🚀 Demo NKP</h1>
            <p class="subtitle">Nutanix Kubernetes Platform</p>
            <p>Déploiement réussi dans le cluster Kubernetes!</p>
            
            <div class="features">
                <div class="feature">
                    <div class="emoji">⚡</div>
                    <h3>Performance</h3>
                    <p>Infrastructure optimisée</p>
                </div>
                <div class="feature">
                    <div class="emoji">🔒</div>
                    <h3>Sécurité</h3>
                    <p>Environnement sécurisé</p>
                </div>
                <div class="feature">
                    <div class="emoji">📊</div>
                    <h3>Monitoring</h3>
                    <p>Surveillance en temps réel</p>
                </div>
            </div>
            
            <div class="timestamp">
                Déployé le: <span id="timestamp"></span>
            </div>
        </div>
        
        <script>
            document.getElementById('timestamp').textContent = new Date().toLocaleString('fr-FR');
        </script>
    </body>
    </html>
