---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami-custom
spec:
  type: "oci"
  interval: 10m
  url: oci://registry-1.docker.io/bitnamicharts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: demo-apache
spec:
  interval: 15s
  releaseName: demo-apache
  chart:
    spec:
      chart: apache
      sourceRef:
        kind: HelmRepository
        name: bitnami-custom
      version: "11.3.4"
  values:
    global:
      security:
        allowInsecureImages: True
    podLabels:
      app: demo-apache
      version: "11.3.4"
    replicaCount: 2
    htdocsConfigMap: indexwebdemo
    extraDeploy:
      - apiVersion: v1
        data:
          index.html: |
            <!DOCTYPE html>
            <html lang="fr">
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>Bienvenue</title>
                <style>
                    body {
                        display: flex;
                        justify-content: center;
                        align-items: center;
                        height: 100vh;
                        background-color: #f0f8ff;
                        font-family: 'Arial', sans-serif;
                        margin: 0;
                    }

                    h1 {
                        color: #4a90e2;
                        font-size: 48px;
                        text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2);
                    }

                    .container {
                        text-align: center;
                        border: 1px solid #4a90e2;
                        padding: 20px;
                        border-radius: 10px;
                        background-color: rgba(255, 255, 255, 0.8);
                    }
                </style>
            </head>
            <body>
                <div class="container">
                    <h1>Apache is working !</h1>
                </div>
            </body>
            </html>
        kind: ConfigMap
        metadata:
          name: indexwebdemo
